export { default as Login } from './LoginPage'
export { default as Homepage } from './Homepage'
export { default as Customer } from './Customer'
export { default as Order } from './Order'
export { default as Package } from './Package'